### ISSUE TITLE
Setting it up on Web

### ISSUE THREAD

**Issue by the-epsd** [keeshii/ryuu-play#1]
Hi there! Is there a full tutorial on how to set this up on the web from start to finish? Similar to https://ptcg.ryuu.eu/

**Comment by keeshii** [comment]
Not yet, but I think it could be useful, so tomorrow I will try to create one.

Thanks for the first valid issue :)

**Comment by keeshii** [comment]
Added my first wiki page in this project:
https://github.com/keeshii/ryuu-play/wiki/Configuration-of-the-HTTP-server

Hope it will solve your problems.
